module.exports = {
  distDir: "nextjs",
  env: {
    FIREBASE_API_KEY: "TODO_YOUR_PROJECT_API_KEY",
    FIREBASE_AUTH_DOMAIN: "TODO_YOUR_PROJECT_AUTH_DOMAIN",
    FIREBASE_DATABASE_URL: "TODO_YOUR_PROJECT_DATABASE_URL",
    FIREBASE_PROJECT_ID: "TODO_YOUR_PROJECT_ID_HERE",
    FIREBASE_STORAGE_BUCKET: "TODO_YOUR_PROJECT_STORAGE_BUCKET",
    FIREBASE_MESSAGING_SENDER_ID: "TODO_YOUR_PROJECT_MESSAGING_SENDER_ID",
    FIREBASE_APP_ID: "TODO_YOUR_PROJECT_APP_ID",
    FIREBASE_MEASUREMENT_ID: "TODO_YOUR_PROJECT_MEASUREMENT_ID",
  },
  experimental: {
    sprFlushToDisk: false,
  },
};
